## Oceanbolt Python SDK - Capesize Iron Ore Imports in China Last 7 Days

Example of Oceanbolt's Python SDK to answer the question - "Which Capesize vessels have discharged iron ore in China over the past 7 days?"

In [12]:
# Import the relevant libraries
# In order to get a timeseries of weekly export volumes, we use the TradeFlows client (https://python-sdk.oceanbolt.com/tradeflows_v3/tradeflows.html)

from oceanbolt.sdk.client import APIClient
from oceanbolt.sdk.data.trade_flows import TradeFlows
from oceanbolt.sdk.data.entities import Regions
from datetime import date,timedelta

In [6]:
# Create the base API client using your token. Tokens can be created in the Oceanbolt App (app.oceanbolt.com)
base_client = APIClient("eyJhbGciOiJSUzI1NiIsImtpZCI6ImUxNmUwNWI1NTZmNjVjYWEyNTg0ODU0N2FmYjNjZjI4IiwidHlwIjoiSldUIn0.eyJhdWQiOiJodHRwczovL2FwaS5vY2VhbmJvbHQuY29tIiwiZXhwIjoxNjQ4MjM1Njc4LCJpYXQiOjE2MTY2OTk3NzAsImlzcyI6Imh0dHBzOi8vYXV0aC5vY2VhbmJvbHQuY29tLyIsImtpZCI6ImUxNmUwNWI1NTZmNjVjYWEyNTg0ODU0N2FmYjNjZjI4Iiwia3R5cGUiOiJhcGlrZXkiLCJvYmtpZCI6IjQxUUFlTE40WlBGeDhHZWoiLCJvcmdpZCI6Im9jZWFuYm9sdCIsInN1YiI6ImF1dGgwfDVkODkzMTRhZDIyN2IxMGQ1YjVjMWM4OCJ9.VFbMqrcFxP5yKHsnjupVwSqFZGlkwYdEppc4antCzRHIrgRJFKVpdCREvRtbQnoKew0qVmO6LEFVbIPcbX-Mf4rRAkL24g457PVsVH-yG4E14USiYJlz1bSkJRd40-aXFFaRDuhUsqqwaRMGCzLLBoxcYzLTX54iglM30xOk0loWomfJXrzrLnAHRzTCXQAIgiQCHA3KQB09akl9_JpTLs3_wzhMuKo2QJrX-qPmLBTCgxvz8ATkmmkzEtBWjXmMDfZY5hSmnsuWNdBjEQR1RWCA6zfoTw-3L_x3tPRW8RGjfWOc8GpKQhTNLC66vdq8rLFFzsn_DeuliFDKLlJLvcPwTys3K-s_7Q8k9aTwS7Wiryp6PFGFGEbN8w8DJi8fHgde4WsitrV64Y2DNkglcz-oHF_FCcNp0JHzMHXia8swQf17yg6tppjds9OPIrMy7F8MtDLF6FFsI5TkmPo0Ij4l_uiDYgIDR_gnpq4EXQpyaW_-6Vmn2D1Na3foU2xBQrn77clp9OBiU2vQ3jJAC6w-Pj5rIB8EYIg1956KenfdKWkfIpBiSkTYI8zuzJsaOeFqpebPgvLqzxx2MfOzAyeCYy_l30hTSFhy680PlNJ9D8rWav9TFtT2iA0LmNyHuHUmikmWZV846FbY-G8rHdGfHLyTDnGrXVpLVL9ZxFU")

In [7]:
# Connect to the relevant Oceanbolt data endpoints using the base client object, ie: TradeFlows
china_iron_client = TradeFlows(base_client)

In [10]:
# We apply filters to our query to get a list of Chinese iron ore imports over the last week
# A complete list of available filters can be found at https://python-sdk.oceanbolt.com/tradeflows_v3/tradeflows.html#arguments

df = china_iron_client.get(
    discharge_country_code=['CN'], #Speficy discharge country as China by using country code "CN"
    commodity_group=['iron ore'], #Speficy to iron ore flows only
    start_date=date.today() - timedelta(days=30), #Speficy today's date and 7 days back in time
    flow_direction="import", #Specify to filter and group on import date
    segment=['capesize'], #Specify vessel segment as Capesizes only
)

#Print 2 first rows of table
df.head(2)

,voyage_id,flow_id,imo,vessel_name,segment,sub_segment,dwt,commodity,commodity_value,commodity_group,...,discharge_port_days_berthed,discharge_port_days_waiting,days_steaming,days_total_duration,distance_calculated,distance_actual,eta,destination,status,parceling
0,0bc2e16766b11d922281160e09029758,d410d0067d2950fbe8e8ee67392e7054,9620530,MEI HUA HAI,Capesize,Babycape (110-140k),115198,Iron Ore (Unclassified),iron_ore_unclassified,Iron Ore,...,3.002,0.17,4.24,10.213,380.1,621.534126,2021-03-17T02:00:00Z,CN CJK,Complete,False
1,df7cbb7d66875d3728c2a3f961a0bf93,03f2775999df3209b0e2bb983177df7a,9497206,MAGSENGER 1,Capesize,Babycape (110-140k),115581,Magnetite,magnetite,Iron Ore,...,1.035,0.755,12.0,16.621,3135.08,3085.77384,2021-03-24T00:30:00Z,ZHOU SHAN CHINA,Waiting to Discharge,False

In [14]:
Regions(base_client).get()

         region_id                 region_name
0               AG                Arabian Gulf
1           BALTIC                      Baltic
2         BLACKSEA                   Black Sea
3        CARRIBEAN                   Carribean
4          CASPIAN                 Caspian Sea
5             CONT                   Continent
6       EASTAFRICA                 East Africa
7             ECCA  East Coast Central America
8          ECINDIA            East Coast India
9             ECSA    East Coast South America
10         EAUSSIE           Eastern Australia
11         EASTMED       Eastern Mediterranean
12         FAREAST                    Far East
13            NCSA   North Coast South America
14        NWAFRICA        North Western Africa
15          REDSEA                     Red Sea
16             SEA             South East Asia
17  SOUTHERNAFRICA             Southern Africa
18            USEC               US East Coast
19             USG                     US Gulf
20            USWC               US West Coast
21            WCCA  West Coast Central America
22         WCINDIA            West Coast India
23            WCSA    West Coast South America
24         WAUSSIE           Western Australia
25         WESTMED       Western Mediterranean